services:
  shell2http:
    build:
      context: .
      dockerfile: Dockerfile
    image: shell2http-meilisearch:latest 
    container_name: shell2http-meilisearch
    ports:
      - "8081:8081"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/meilisearch
    
